#!/bin/bash
# Copyright 2015 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# Create a cluster (set of VMs) to eventually run POD(s).

set -eu

CLUSTER_NAME="$1"

NUM_NODES=1

# - https://cloud.google.com/compute/docs/machine-types
# - VM ubuntu-14-04 starts with 486Mib of RAM used.
# 1/8 core; 0.6GB RAM; 0.008$/h; to use it when NUM_NODES < 3, you need to use:
#     --no-enable-cloud-logging --no-enable-cloud-monitoring
#VM_TYPE=f1-micro
# 1/2 core; 1.7GB RAM; 0.027$/h
VM_TYPE=g1-small
# 1 core; 3.75GB RAM; 0.05$/h
#VM_TYPE=n1-standard-1

# Disk:
# - VM disk is 4¢/GB/mo. Read & write are free.
# - Google Cloud Storage Standard is 2.6¢/GB/mo
#   Nearline is 1¢/GB/mo but 1¢/GB extra to read back
#   https://cloud.google.com/storage/docs/nearline
#   https://cloud.google.com/storage/pricing#storage-pricing
#
# Reading from Cloud Storage or a VM:
#   Read back is 12¢/GB (!) for network egress.
#   EC2 is 9¢/GB; https://aws.amazon.com/ec2/pricing/;
#   https://aws.amazon.com/cloudfront/pricing/ is 8.5¢/GB
# Note that the size is implicitly in GB.
VM_DISK_SIZE=10

# In addition, there's a load balancer cost:
#   https://cloud.google.com/compute/docs/load-balancing/
#   0.8¢/GB + 2.5¢/h.

# gcloud container --help
gcloud container clusters create "$CLUSTER_NAME" \
  --num-nodes $NUM_NODES \
  --disk-size "$VM_DISK_SIZE" \
  --machine-type "$VM_TYPE"

echo 'VMs currently live:'
gcloud compute instances list
