#!/bin/bash
# Copyright 2015 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# Deletes the POD (the application) without deleting the hosting VMs (cluster).

set -eu

NODE_NAME="$1"

# Stop the pod.
kubectl stop rc "$NODE_NAME"
# Delete the server and the external load balancer.
kubectl delete services "$NODE_NAME"

echo 'Remaining pods:'
kubectl get pods
