#!/bin/bash
# Copyright 2015 Marc-Antoine Ruel. All rights reserved.
# Use of this source code is governed under the Apache License, Version 2.0
# that can be found in the LICENSE file.

# Deletes the cluster.

set -eu

CLUSTER_NAME="$1"

gcloud container clusters delete "$CLUSTER_NAME"

echo 'Clusters remaining:'
gcloud container clusters list
